apiVersion: apps/v1
kind: Deployment
metadata:
  name: "transaction-ms"
spec:
  selector:
    matchLabels:
      app: "transaction-ms"
  replicas: 2
  template:
    metadata:
      labels:
        app: "transaction-ms"
    spec:
      containers:
        - image: bermondjon/pub-boss-trns-service
          imagePullPolicy: Always
          name: "transaction"
          ports:
            - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: "transaction-ms"
spec:
  ports:
    - port: 8080
      targetPort: 8081
      protocol: TCP
  type: NodePort
  selector:
    app: "transaction-ms"